ALTER TABLE PRODUCTS DROP CONSTRAINT fk_id_productCategory;

ALTER TABLE EMPLOYEES DROP CONSTRAINT fk_id_job;

ALTER TABLE EMPLOYEES DROP CONSTRAINT fk_id_store_employees;

ALTER TABLE INGREDIENTS_PRODUCTS DROP CONSTRAINT fk_id_ingredient;

ALTER TABLE INGREDIENTS_PRODUCTS DROP CONSTRAINT fk_id_product_ingredients_products;

ALTER TABLE ORDERS_HEADER DROP CONSTRAINT fk_id_paymentMethod;

ALTER TABLE ORDERS_HEADER DROP CONSTRAINT fk_id_customer;

ALTER TABLE ORDERS_LINE DROP CONSTRAINT fk_id_product_orders_line;

ALTER TABLE ORDERS_LINE DROP CONSTRAINT fk_id_orderHeader;

DROP TABLE STORES;

DROP TABLE PRODUCT_CATEGORIES;

DROP TABLE PRODUCTS;

DROP TABLE INGREDIENTS;

DROP TABLE ORDERS_LINE;

DROP TABLE ORDERS_HEADER;

DROP TABLE INGREDIENTS_PRODUCTS;

DROP TABLE PAYMENT_METHODS;

DROP TABLE CUSTOMERS;

DROP TABLE EMPLOYEES;

DROP TABLE JOBS;
